### ISSUE TITLE
Issues with contenteditable on IE11

### ISSUE THREAD

**Issue by andrewborstein** [zurb/tribute#171]
## Can't add multiple mentions

**How can we reproduce this bug?**

1. Visit https://zurb.github.io/tribute/example on IE 11
2. Successfully add a mention to the contenteditable field
3. Attempt to add a second mention in the same field

**What did you expect to happen?**

Second mention is added

**What happened instead?**

Mention suggestions appear but cannot be selected. Attempting to click a suggestion dismisses the modal without inserting a mention in the contenteditable field. 

**Link (jsfiddle/plunkr/codepen) or Screenshot:**

![dec-10-2018 10-15-23](https://user-images.githubusercontent.com/7654254/49744017-f95a2400-fc69-11e8-8374-cc06ed774c1a.gif)

## Can only add mention when initialized by first character

**How can we reproduce this bug?**

1. Visit https://zurb.github.io/tribute/example on IE 11
2. Type some plain text in the contenteditable field, e.g. `Hey `
3. Attempt to add a mention after the plain text

**What did you expect to happen?**

Mention added

**What happened instead?**

Mention suggestions appear but cannot be selected. Attempting to click a suggestion dismisses the modal without inserting a mention in the contenteditable field. 

**Link (jsfiddle/plunkr/codepen) or Screenshot:**

![dec-10-2018 11-23-13](https://user-images.githubusercontent.com/7654254/49745914-08db6c00-fc6e-11e8-93ed-6c65aab837a0.gif)

Unfortunately IE11 support is non-negotiable for me, and that's why I was so excited to see that Tribute supports IE9+. The same behavior is present for both of these issues on https://codepen.io/mrsweaters/full/OxxdWv as well.

**Comment by mrsweaters** [comment]
I think these issues have been resolved as I'm no longer to reproduce them. Can you test against master and confirm? Thank you for filing!

**Comment by mrsweaters** [comment]
I have pushed these updates to version `3.5.0`. Let me know if that works for you!

**Comment by ashwin1014** [comment]
> 
> 
> I have pushed these updates to version `3.5.0`. Let me know if that works for you! Feel free to reopen the issue if it doesn't.

The issue still exists for Internet Explorer 11. Tested version 3.6.0
