### ISSUE TITLE
Tribute container does not reopen after searching for a non-existing value

### ISSUE THREAD

**Issue by lcwalther** [zurb/tribute#385]
**How can we reproduce this bug?**

1. Step one
Trigger the tribute component, e.g. by pressing "@"
2. Step two
Type in a letter combination that exists in the values array, e.g. "Jor". "Jordan Hemphrey" is shown.
3. Step three
Add an "f" so that you typed in "Jorf" which is a combination that does not exist in the values array. The tribute container disappears.
4. Step four
Press backspace to delete the "f", so that only "Jor" is displayed. 

**What did you expect to happen?**
The tribute container should reappear, showing "Jordan Hemphrey", basically showing all available options starting with "Jor".

**What happened instead?**
The tribute container does not reopen. The user has to delete the whole value "@Jor", even including the "@" symbol, and type it in again to retrigger the tribute container and search for another value.

**Link (jsfiddle/plunkr/codepen) or Screenshot:**
![image](https://user-images.githubusercontent.com/46449694/72168410-68ee9580-33cd-11ea-8639-981bbc4f7718.png)

**Comment by NitzanShifrin** [comment]
Any progress with that?

**Comment by NitzanShifrin** [comment]
@hyojin, are you planning to work on it soon?

**Comment by hyojin** [comment]
@NitzanShifrin Hi, I did quickly go through the code and it seems it's intended behavior (at least with the current code). Unfortunately, I don't know the background of this 🤔

**Comment by mxgl** [comment]
I got around this with this code

```js
 selectTemplate: function (item) {
    if(item) {
       return '@' + item.original.name;
    } else {
       // required to prevent lockup and console error when pressing enter/tab on no match found
       return '@' + this.current.mentionText;
    }
 },
 noMatchTemplate: function() {
    return '<li>No Match Found!</li>';
 },
```

**Comment by mrsweaters** [comment]
@mxgl Should we update the default `selectTemplate` to return the current mentionText on no match?

**Comment by mxgl** [comment]
That's what I do

It creates a scenario where typing `@abc<space>` leaves the `@abc ` in the textarea rather than erasing the mention entirely.

Also, having the noMatchTemplate defined by default keeps the menu open the entire time, allowing backspacing back to a search with results to function more smoothly!

**Comment by mxgl** [comment]
Can you make it return 

`return this.current.collection.trigger + this.current.mentionText;`

In case there's a different trigger.

**Comment by mrsweaters** [comment]
Done!

**Comment by lcwalther** [comment]
Sorry, I really appreciate the effort you put on this library but this did not fix the main bug. The problem is that the current behaviour is _inconsistent_ when the noMatchTemplate returns an empty string (which is a requirement in my case, not to show the noMatchTemplate). 
When you type something that exists and you delete a character, the list of results is still shown but as soon you type a word that does not exist, the whole list is removed, even if it was the same word that returned results before. Is that inconsistency expected?

**Comment by mxgl** [comment]
@lcwalther is there a reason an empty noMatchTemplate is required?

You could try 
```noMatchTemplate: function () {
    return '<span style:"visibility: hidden;"></span>;
}```

**Comment by mrsweaters** [comment]
@mxgl's workaround seems to work. I'll add that to the docs.

**Comment by lcwalther** [comment]
@mxgl @mrsweaters I tried it, but with this an empty list is shown instead of nothing at all, which is what I need in my case.

**Comment by mrsweaters** [comment]
Could you explain your use case a little bit more? Why do you need nothing rendering? You could add a class to it and set `pointer-events: none` if you are worried about someone interacting with it.

**Comment by lcwalther** [comment]
Yes, exactly, I want the `ul` removed because it looks like this, when using `<span style:"visibility: hidden;"></span>`:
![image](https://user-images.githubusercontent.com/46449694/76349709-ca1de100-630a-11ea-8063-06261dfc4248.png)

Basically, I want the same behaviour as when e.g. mentioning users here in this comment window on Github.

**Comment by mrsweaters** [comment]
What if we add a class to the `ul`, like `tribute-no-match` so you can hide it?

**Comment by lcwalther** [comment]
Sorry for getting back to you so late @mrsweaters 
Would this class be only added to the `ul` when there is no match? Then this solution would be perfect!

**Comment by halloei** [comment]
> What if we add a class to the `ul`, like `tribute-no-match` so you can hide it?

Looking forward to this, too!

**Comment by sf-john-kim** [comment]
+1 

Facing the same problem as OP. The expected UX is already implemented in GitHub as well. Try typing @ on the comment section right now and you can experience it. (When you get no match, then delete a char, then it will show the results that was showing before char was typed in the first place, instead of continuing to showing "No Match")

**Comment by sf-john-kim** [comment]
Sorry the workaround isn't working for me.. OP's issue is unresolved. 😢 
Would love to get this somehow fixed... 🙇
