### ISSUE TITLE
Search is not fired after Backspace, when previous result is empty

### ISSUE THREAD

**Issue by TetianaP** [zurb/tribute#53]
**How can we reproduce this bug?**

1. Step one
Create a simple `<div class="mentionable">Some text.</div>`
and initialize a tribute `var tribute = new Tribute({ values: [ {key: 'Phil Heartman', value: 'pheartman'}, {key: 'Gordon Ramsey', value: 'gramsey'} ]});`
Apply tribute to the element `tribute.attach(document.querySelectorAll('.mentionable'));`

2. Step two
Start typing `@P` - 'Phil Heartman' option is shown
![image](https://cloud.githubusercontent.com/assets/21356403/22350101/6df7eb92-e477-11e6-8259-a43eaf5b64a6.png)
Type anything (not to match the option) `@Py` - no option is shown
![image](https://cloud.githubusercontent.com/assets/21356403/22350088/5f5eeda6-e477-11e6-8d62-a83504164fb4.png)

3. Step three
Press Backspace -  `@P` text is left

**What did you expect to happen?**
'Phil Heartman' option is shown

**What happened instead?**
No option is shown. Need to type something again for search to be called.

**Link (jsfiddle/plunkr) or Screenshot:**
![image](https://cloud.githubusercontent.com/assets/21356403/22350035/1ebfd864-e477-11e6-9026-5a68d0cd0149.png)

**Comment by mrsweaters** [comment]
@TetianaP Did you test this against master? I think this may have been fixed as I'm not able to reproduce it there. Can you try master as well? If its working I'll go ahead and cut a new release.

**Comment by TetianaP** [comment]
Reproduced on the latest version available through npm install - v2.3.1.
Is it different from master?

**Comment by mrsweaters** [comment]
Yeah, master is more up to date than the latest release.

**Comment by mrsweaters** [comment]
@TetianaP I've pushed up `2.3.2`. Let me know if that fixes your issue!

**Comment by TetianaP** [comment]
Checked on new version 2.3.2. The issue can still be reproduced.

**Comment by mrsweaters** [comment]
Fixed in V3

**Comment by TetianaP** [comment]
@mrsweaters please reopen this issue.
It was tested on V3, and it is not fixed.

**Comment by mrsweaters** [comment]
It appears that the default `noMatchTemplate` is not working correctly. If i define a custom noMatchTemplate, the problem goes away. Working on a solution.

**Comment by mrsweaters** [comment]
This should fix it! https://github.com/zurb/tribute/commit/baf3df5af87598fe3f88f178fd1368bdfd84c312

I've pushed this to master and it will get released in 3.0.1.

**Comment by TetianaP** [comment]
Thank you! Looks like it fixes the issue, unfortunately causing a few new ones:
1. there is no way to hide menu when no item matches
2. user can click on 'No Match!' item and logic for selecting item is triggered, causing errors

Could you please have a look on these? Or should i create a separate request?

**Comment by mrsweaters** [comment]
I'll take a look at those couple of issues as well!

**Comment by mrsweaters** [comment]
@TetianaP Fixed in https://github.com/zurb/tribute/releases/tag/3.1.0, thank you!

**Comment by mrsweaters** [comment]
@benediktveith Should be working now. Give `3.5.3` a try.

**Comment by benediktveith** [comment]
@mrsweaters Looks good, thanks 👍

**Comment by ReneS1991** [comment]
@mrsweaters It looks like the fix ain't working anymore? I tried on https://zurb.github.io/tribute/example/ but I got the same issue there.

In the example, when I type `@j` I get the dropdown, then when I add a B (`@jb`) I don't get any results and therefore no dropdown, then when I backspace to get back to `@j` it doesn't show the dropdown.

I'm using version `3.7.3` in my project.

**Comment by mrsweaters** [comment]
@ReneS1991 There were some changes around noMatchTemplate recently, this may have affected this behavior.

**Comment by ReneS1991** [comment]
Okay, any idea if the behaviour will get fixed in the (near) future?

**Comment by sf-john-kim** [comment]
+1 ...
